### PR TITLE
feat: Adjust log verbosity via verbose arg

### PR DESCRIPTION
**Pull request by VitaminB16**
I often don't want any logs printed when the code is executed, so being able to control the verbosity is useful for me.

### CODE REVIEW

**Comment by cullenwatson** [comment]
I believe you can do this by just

```
import logging
logger = logging.getLogger('JobSpy')
logger.setLevel(logging.WARNING)
````

I set it to INFO level by default as I believe for most people they would rather see it by default.

**Comment by VitaminB16** [comment]
That's a fair point and it works, I just thought it would be useful to have a `verbose` parameter in a similar way to how some other libraries implement this

**Comment by cullenwatson** [comment]
I see, what libraries do this?

**Comment by VitaminB16** [comment]
I see it mostly in ML libraries where the printouts can be massive, e.g. [https://xgboost.readthedocs.io/en/stable/parameter.html](XGBoost) [Tensorflow],(https://www.tensorflow.org/api_docs/python/tf/keras/Model), [scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html)

**Comment by cullenwatson** [comment]
makes sense

**Pull request merged**
