### PR TITLE
format: Apply Black formatter to the codebase

### PR DESCRIPTION
**Pull request by VitaminB16**
Applied Black formatter to the codebase.

All logic is completely untouched, but some small juggling was made in some places to reduce the number of lines.

Also added text to the error messages (for `logger.error(err)`).

I hope this number of changes does not mess up anything you are working on at the moment, though it should be modular enough to make merging easier.

### CODE REVIEW

**Comment by cullenwatson** [comment]
Is there a script we could add to format the code add before any commits?

**Comment by VitaminB16** [comment]
Yes it is possible with a pre-commit, I can add a commit for it now

**Comment by VitaminB16** [comment]
Now to use this pre-commit the developer needs to install it using `pre-commit install`. Then if a changed file is not formatted correctly, pre-commit will add the formatted files as unstaged changes, which will need to be staged and recommitted.

**Comment by cullenwatson** [comment]
sick!!

**Pull request merged**
